### ISSUE TITLE
[Bugs] Few reported issues on dark mode!

### ISSUE THREAD

**Issue by karandatwani92** [Laravel-Backpack/theme-tabler#160]
### Bugs
- [ ] [Can't see what you're typing (Dark theme, Filter feature, Select2 type)](https://github.com/Laravel-Backpack/community-forum/issues/852)
- [ ] [Visibility issue](https://github.com/Laravel-Backpack/community-forum/issues/851)
- [ ] [Modal cancel button color correction](https://github.com/Laravel-Backpack/community-forum/issues/850)

**Comment by pxpm** [comment]
Fixed in 1.2.4, a composer update should get the fixes.

**Comment by tringuyenduc2903** [comment]
Dear @pxpm 

I still see the [Modal cancel button color correction](https://github.com/Laravel-Backpack/community-forum/issues/850) error. Are you missing anything?

Also, test bulk-button, delete-button, I see you often fix 1 problem but break something else

**Comment by pxpm** [comment]
> I see you often fix 1 problem but break something else...

That's how I keep my job, don't tell @tabacitu 🤫 

Jokes aside, sorry I probably missed it, I will have a look at it again, thanks for the heads up 🙏

**Comment by pxpm** [comment]
@tringuyenduc2903 the cancel button on the swals should now be visible as expected. 

Let me know if I missed any. 

PS: it required updates in theme tabler, crud and pro. so make sure you are using 1.2.7, 6.6.6 and 2.1.8 in case you use pro too. 

Cheers
