### ISSUE TITLE
[Bug] Fix scrollbar issue

### ISSUE THREAD

**Issue by maurohmartinez** [Laravel-Backpack/theme-tabler#31]
# Bug report

Everything on this [conversation](https://github.com/Laravel-Backpack/theme-tabler/pull/19#discussion_r1162574292).

![](https://user-images.githubusercontent.com/33960976/233013391-24be69fc-e3ee-451c-ae86-2446de55c054.png)

Last comment from @tabacitu:

-------
Seems like we have no good options 😔 What if we don't customize it at all?! I mean... what I would like, to be honest, is to have the MacOS behaviour. The scrollbar appears when you scroll.

I guess what we have here is better than the regular UX on Windows, where the scrollbar is probably ugly AF... but it doesn't really make sense on MacOS. So maybe... we leave it like Tabler did it on Windows (always visible, or at least the gutter)... and just don't customize anything on MacOS?!

We need some extra eyes on this with different operating systems. @promatik ? @pxpm ? What's the Windows perspective on this?

**Comment by pxpm** [comment]
![image](https://github.com/Laravel-Backpack/theme-tabler/assets/7188159/cce67421-6dd0-4cbb-b762-0d6e4c8266da)

It seems that in beta19 this behavior has changed and now works fine when there is no sidebar, but if the content is loaded with ajax and later require the sidebar there is a small flick.

**Comment by tabacitu** [comment]
Update: we fixed the flick... with a sledgehammer: https://github.com/Laravel-Backpack/theme-tabler/commit/41bf444e87a1d88042eb55f98ac73d6d04a13c5d

I still think we should find a way to fix this. Maybe the whole idea of customizing the looks of the scrollbar wasn't a good one.

Normally:
- scrollbars look bad on Windows
- scrollbars are invisible or pretty on Mac OS and iOS

Now:
- scrollbars look prettier than expected on Windows
- scrollbars look less pretty than expected on MacOS and iOS (and don't auto-hide as expected)

So it seems like the solution was to downgrade the experience of some users, for the benefit of others. Granted I'm biased because my experience got downgraded 😅 But I think it was the bad move. What if we remove `simplebar` and all style customizations? Won't that at least be _as expected_ for all parties? Won't that be better than having surprises?

**Comment by promatik** [comment]
Quick update on this one;
1) We cannot undo the changes to scrollbar added by tabler — it's a css rule by design 🤷‍♂️
2) Simplebar does not solve our issue, it creates more instead 😅

---

Our options:
1) Do nothing, the page "jumps" when the content changes.
2) Force the `overflow-y: scroll` as it is now.
3) Request a change on tabler (I believe it's unlikely to be accepted).
4) Modify the tabler.min.css to remove the scrollbar customization (we'll need to do it every time we update tabler).

**Comment by tabacitu** [comment]
Ok so for now... let's go with no 2. It's what we have... we just might get used to it. It is what it is.
